#!/usr/bin/env python3
"""Generate the dev-flavor weekday prayer text constants from pinned snapshots."""

from __future__ import annotations

import unicodedata
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "content" / "sources" / "baladi-wikisource"
OUTPUT = (
    ROOT
    / "app"
    / "src"
    / "dev"
    / "java"
    / "io"
    / "github"
    / "gilnetizen"
    / "aseh"
    / "FlavorWeekdayPrayerTexts.kt"
)


def paragraphs(name: str) -> list[str]:
    source = (SOURCE / name).read_text(encoding="utf-8")
    return [line.strip() for line in source.splitlines() if line.strip()]


def runtime_text(lines: list[str]) -> str:
    text = "\n\n".join(lines).strip()
    text = unicodedata.normalize("NFKC", text)
    text = text.replace(" | ", " ")
    text = re.sub(r"\[/([^\]]+)\]", r"(אוֹ: \1)", text)
    text = text.replace("(בעשי\"ת אומר ללא יועיל ואנחנו וכו')", "")
    return text


def main() -> None:
    shacharit = paragraphs("shacharit.rev3081633.display.txt")
    mincha = paragraphs("mincha.rev1076941.display.txt")
    arvit = paragraphs("arvit.rev2947373.display.txt")

    amidah_indices = [
        251,
        252,
        254,
        255,
        *range(257, 271),
        272,
        273,
        275,
        276,
        278,
        279,
        282,
        284,
        285,
        287,
        290,
        291,
        292,
    ]
    selections = {
        "SHACHARIT_MORNING_TEXT": [
            line for index, line in enumerate(shacharit[0:32]) if index != 8
        ],
        "SHACHARIT_TORAH_TEXT": [
            line for index, line in enumerate(shacharit[32:59], 32) if index != 41
        ],
        "SHACHARIT_ZEMIROT_ONE_TEXT": shacharit[59:140],
        "SHACHARIT_ZEMIROT_TWO_TEXT": shacharit[140:237],
        "SHACHARIT_SHEMA_TEXT": [
            line for index, line in enumerate(shacharit[237:251], 237) if index != 248
        ],
        "WEEKDAY_AMIDAH_TEXT": [shacharit[index] for index in amidah_indices],
        "MINCHA_OPENING_TEXT": mincha[8:13],
        "MINCHA_TACHANUN_TEXT": [mincha[63], mincha[65]],
        "MINCHA_EVENING_PSALMS_TEXT": mincha[67:99],
        "ARVIT_BLESSINGS_TEXT": [arvit[0], arvit[3], arvit[4]],
        "ARVIT_SHEMA_TEXT": arvit[5:15],
        "ARVIT_CLOSE_PSALMS_TEXT": arvit[54:57],
        "ALEINU_TEXT": arvit[58:60],
    }

    output = [
        "package io.github.gilnetizen.aseh",
        "",
        "// Generated by tools/generate_weekday_prayer_texts.py from pinned source snapshots.",
        "// Keep selection changes synchronized with the source manifest and review notes.",
        "",
    ]
    for name, selected_lines in selections.items():
        output.append(f'internal val {name} = """')
        output.extend(runtime_text(selected_lines).splitlines())
        output.append('""".trimIndent()')
        output.append("")

    OUTPUT.write_text("\n".join(output), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
